cmake_minimum_required(VERSION 3.16)
project(IMakeCoreTests LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)

add_subdirectory(advanced_resolve/project_default)
add_subdirectory(advanced_resolve/project_publisher)
add_subdirectory(advanced_resolve/project_trans_ver)
add_subdirectory(advanced_resolve/project_two)
add_subdirectory(basic_resolve/project_single)
add_subdirectory(basic_resolve/project_skip)
add_subdirectory(basic_resolve/project_source)
add_subdirectory(basic_resolve/project_transitive)
add_subdirectory(basic_resolve/project_version)
add_subdirectory(cmake_output/project_cmake_single)
add_subdirectory(cmake_output/project_cmake_trans)
add_subdirectory(cmake_output/project_cmake_ver)
add_subdirectory(local_origin/project_local)
add_subdirectory(local_origin/project_local_first)
# add_subdirectory(local_origin/project_local_missing)
add_subdirectory(local_origin/project_local_second)
add_subdirectory(path_resolve/project_path)
# add_subdirectory(path_resolve/project_path_bad)
add_subdirectory(path_resolve/project_path_src)
add_subdirectory(static_chain/project_source_explicit)
add_subdirectory(static_chain/project_source_static)
# add_subdirectory(static_chain/project_static_chain)
# add_subdirectory(static_chain/project_static_dynamic)
# add_subdirectory(static_chain/project_static_source_dep)
# add_subdirectory(static_propagation/project_static)
# add_subdirectory(static_propagation/project_static_cpp)
# add_subdirectory(validation/project_err_dynamic)
# add_subdirectory(validation/project_err_missing)
# add_subdirectory(validation/project_err_static)
# add_subdirectory(validation/project_no_pkg)
add_subdirectory(version_specifiers/project_exact)
add_subdirectory(version_specifiers/project_range_low)
add_subdirectory(version_specifiers/project_range_restricted)
# add_subdirectory(version_specifiers/project_skip)
add_subdirectory(version_specifiers/project_wildcard)

