#!/bin/bash
set -euo pipefail

APP_NAME="IMakeCore"
DEFAULT_INSTALL_DIR="/opt/$APP_NAME"
TARGET="$DEFAULT_INSTALL_DIR"
ENV_FILE="/etc/profile.d/imakecore_vars.sh"

# ── 权限检查 ──────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
    echo "Requesting root privileges..."
    exec sudo "$0" "$@"
    exit $?
fi

# ── 确定安装目标 ──────────────────────────────
echo ""
echo "IMakeCore Linux Installer"
echo "─────────────────────────────"
echo "Target: $TARGET"

# ── 清理旧目录 ────────────────────────────────
if [ -d "$TARGET" ]; then
    echo "Removing existing installation..."
    rm -rf "$TARGET" || { echo "ERROR: Cannot remove $TARGET"; exit 1; }
fi
mkdir -p "$TARGET" || { echo "ERROR: Cannot create $TARGET"; exit 1; }

# ── 拷贝文件 ──────────────────────────────────
echo "Copying files..."
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
cp -r "$SCRIPT_DIR"/* "$TARGET/" || { echo "ERROR: Copy failed"; exit 1; }
echo "  OK: files copied to $TARGET"

# ── 注册环境变量 ──────────────────────────────
echo ""
echo "Registering environment variables..."

IMAKECORE_ROOT="$TARGET"
IQMakeCore="$TARGET/.system/.IMakeCore.prf"
ICMakeCore="$TARGET/.system/.IMakeCore.cmake"
IMAKECORE_BIN="$TARGET/.programs/linux"

# 1) /etc/profile.d/ — 新交互式 shell (login shells)
cat > "$ENV_FILE" << PROFILEEOF
# IMakeCore — auto-generated by linux_install.sh
export IMAKECORE_ROOT="$IMAKECORE_ROOT"
export IQMakeCore="$IQMakeCore"
export ICMakeCore="$ICMakeCore"
if [ -d "$IMAKECORE_BIN" ]; then
    export PATH="$IMAKECORE_BIN:\$PATH"
fi
PROFILEEOF
chmod 644 "$ENV_FILE"
echo "  OK: $ENV_FILE"

# 2) /etc/environment — 所有进程 (systemd, cron, GUI)
ENV_SYS="/etc/environment"
if [ -f "$ENV_SYS" ]; then
    cp "$ENV_SYS" "${ENV_SYS}.bak.imakecore"
    # 移除旧 IMakeCore 行
    grep -vE "^(IMAKECORE_ROOT|IQMakeCore|ICMakeCore)=" "$ENV_SYS" > "${ENV_SYS}.tmp" 2>/dev/null || true
else
    touch "${ENV_SYS}.tmp"
fi
{
    cat "${ENV_SYS}.tmp"
    echo "IMAKECORE_ROOT=\"$IMAKECORE_ROOT\""
    echo "IQMakeCore=\"$IQMakeCore\""
    echo "ICMakeCore=\"$ICMakeCore\""
} > "$ENV_SYS"
rm -f "${ENV_SYS}.tmp"
chmod 644 "$ENV_SYS"
echo "  OK: $ENV_SYS"

# 3) 当前 shell — 立即可用
export IMAKECORE_ROOT="$IMAKECORE_ROOT"
export IQMakeCore="$IQMakeCore"
export ICMakeCore="$ICMakeCore"
echo "  OK: current shell"

# ── 验证持久化 ────────────────────────────────
echo ""
echo "Verifying persistence..."

verify_var() {
    local name="$1" expected="$2" source_file="$3"
    local actual
    actual=$(grep "^${name}=" "$source_file" 2>/dev/null | cut -d= -f2- | tr -d '"')
    if [ "$actual" = "$expected" ]; then
        echo "  OK: $name persisted in $(basename "$source_file")"
        return 0
    else
        echo "  FAIL: $name in $(basename "$source_file") — expected '$expected', got '$actual'"
        return 1
    fi
}

FAILED=0
verify_var IMAKECORE_ROOT "$IMAKECORE_ROOT" "$ENV_FILE" || FAILED=1
verify_var IQMakeCore "$IQMakeCore" "$ENV_FILE" || FAILED=1
verify_var ICMakeCore "$ICMakeCore" "$ENV_FILE" || FAILED=1

if [ $FAILED -ne 0 ]; then
    echo "ERROR: Environment persistence verification failed."
    exit 1
fi

# ── 验证当前 shell ─────────────────────────────
echo ""
echo "Verifying current shell..."

[ -n "${IMAKECORE_ROOT-}" ] && echo "  OK: IMAKECORE_ROOT = $IMAKECORE_ROOT" || { echo "  FAIL: IMAKECORE_ROOT not set"; exit 1; }
[ -n "${IQMakeCore-}" ]     && echo "  OK: IQMakeCore     = $IQMakeCore"     || { echo "  FAIL: IQMakeCore not set";     exit 1; }
[ -n "${ICMakeCore-}" ]     && echo "  OK: ICMakeCore     = $ICMakeCore"     || { echo "  FAIL: ICMakeCore not set";     exit 1; }

# ── 符号链接 (程序到 PATH) ─────────────────────
if [ -d "$IMAKECORE_BIN" ]; then
    echo ""
    echo "Creating symlinks..."
    mkdir -p /usr/local/bin
    for prog in "$IMAKECORE_BIN"/*; do
        if [ -f "$prog" ] && [ -x "$prog" ]; then
            name=$(basename "$prog")
            ln -sf "$prog" "/usr/local/bin/$name" 2>/dev/null && echo "  OK: $name -> /usr/local/bin/$name" || echo "  WARN: cannot symlink $name"
        fi
    done
fi

# ── 完成 ──────────────────────────────────────
echo ""
echo "========================================="
echo "IMakeCore installation complete."
echo "========================================="
echo ""
echo "  Target:   $TARGET"
echo "  Env file: $ENV_FILE"
echo "  Sys file: $ENV_SYS"
echo ""
echo "Current shell has environment variables ready."
echo "New shells will auto-load them on login."
echo ""
exit 0
