INCLUDEPATH += $$PWD

HEADERS += \
    $$PWD/http/IHttpAbort.h \
    $$PWD/http/IHttpAnnomacro.h \
    $$PWD/http/IHttpConstant.h \
    $$PWD/http/IHttpCookieJar.h \
    $$PWD/http/IHttpCookiePart.h \
    $$PWD/http/IHttpHeaderJar.h \
    $$PWD/http/IHttpJarUnit.h \
    $$PWD/http/IHttpManage.h \
    $$PWD/http/IHttpMultiPart.h \
    $$PWD/http/IHttpMultiPartJar.h \
    $$PWD/http/IHttpServer.h \
    $$PWD/http/IHttpSession.h \
    $$PWD/http/IHttpTaskCatagory.h \
    $$PWD/http/IRequest.h \
    $$PWD/http/IResponse.h \
    $$PWD/http/action/IHttpActionInterface.h \
    $$PWD/http/action/IHttpActionMappingInterface.h \
    $$PWD/http/action/IHttpActionMappingWare.h \
    $$PWD/http/action/IHttpActionWare.h \
    $$PWD/http/action/IHttpBadRequestAction.h \
    $$PWD/http/action/IHttpInternalErrorAction.h \
    $$PWD/http/action/IHttpInvalidRequestAction.h \
    $$PWD/http/action/IHttpNotFoundAction.h \
    $$PWD/http/action/IHttpOptionsMethodAction.h \
    $$PWD/http/action/IHttpOptionsMethodHandlerInterface.h \
    $$PWD/http/action/IHttpOptionsMethodHandlerWare.h \
    $$PWD/http/biscuits/IHttpAttribute.h \
    $$PWD/http/biscuits/IHttpHeader.h \
    $$PWD/http/biscuits/IHttpMethod.h \
    $$PWD/http/biscuits/IHttpMime.h \
    $$PWD/http/biscuits/IHttpRegistMimeInterface.h \
    $$PWD/http/biscuits/IHttpStatus.h \
    $$PWD/http/biscuits/IHttpVersion.h \
    $$PWD/http/callable/IHttpArgumentType.h \
    $$PWD/http/callable/IHttpCallable.h \
    $$PWD/http/callable/IHttpReturnType.h \
    $$PWD/http/callable/detail/IHttpArgumentTypeDetail.h \
    $$PWD/http/callable/detail/IHttpReturnTypeDetail.h \
    $$PWD/http/controller/IHttpControllerAbort.h \
    $$PWD/http/controller/IHttpControllerAction.h \
    $$PWD/http/controller/IHttpControllerActionMapping.h \
    $$PWD/http/controller/IHttpControllerInterface.h \
    $$PWD/http/controller/IHttpControllerNode.h \
    $$PWD/http/controller/detail/IHttpControllerCallableInfo.h \
    $$PWD/http/controller/pp/IControllerPreProcessor.h \
    $$PWD/http/controller/pp/IDeleteMappingPreProcessor.h \
    $$PWD/http/controller/pp/IGetMappingPreProcessor.h \
    $$PWD/http/controller/pp/IPatchMappingPreProcessor.h \
    $$PWD/http/controller/pp/IPostMappingPreProcessor.h \
    $$PWD/http/controller/pp/IPutMappingPreProcessor.h \
    $$PWD/http/detail/IHttpChunkedFlow.h \
    $$PWD/http/detail/IHttpRequestImpl.h \
    $$PWD/http/detail/IHttpRequestRaw.h \
    $$PWD/http/detail/IHttpResponseHeader.h \
    $$PWD/http/detail/IHttpResponseRaw.h \
    $$PWD/http/detail/task/IHttpDefaultProfileTask.h \
#    $$PWD/http/detail/task/IHttpFileServiceTask.h \
    $$PWD/http/detail/task/IHttpPrintTraceTask.h \
    $$PWD/http/detail/task/IHttpResolverFactory.h \
    $$PWD/http/filter/IHttpBodyFilterInterface.h \
    $$PWD/http/filter/IHttpCompletionFilterInterface.h \
    $$PWD/http/filter/IHttpFilterInterface.h \
    $$PWD/http/filter/IHttpFilterWare.h \
    $$PWD/http/filter/IHttpFirstLineFilterInterface.h \
    $$PWD/http/filter/IHttpHeaderFilterInterface.h \
    $$PWD/http/filter/IHttpPostHandleFilterInterface.h \
    $$PWD/http/filter/IHttpPreHandleFilterInterface.h \
    $$PWD/http/invalid/IHttpBadRequestInvalid.h \
    $$PWD/http/invalid/IHttpInternalErrorInvalid.h \
    $$PWD/http/invalid/IHttpInvalidHandlerInterface.h \
    $$PWD/http/invalid/IHttpInvalidHandlerWare.h \
    $$PWD/http/invalid/IHttpInvalidInterface.h \
    $$PWD/http/invalid/IHttpInvalidWare.h \
    $$PWD/http/invalid/IHttpNotFoundInvalid.h \
    $$PWD/http/path/IHttpPath.h \
    $$PWD/http/path/IHttpPathFragment.h \
    $$PWD/http/path/IHttpPathValidatorInterface.h \
#    $$PWD/http/path/detail/IHttpPathDetail.h \
    $$PWD/http/path/detail/IHttpPathFragmentDetail.h \
    $$PWD/http/path/detail/IHttpPathValidatorsTask.h \
    $$PWD/http/response/IBytesResponse.h \
    $$PWD/http/response/IFileResponse.h \
    $$PWD/http/response/IHtmlResponse.h \
    $$PWD/http/response/IHttpResponseInterface.h \
    $$PWD/http/response/IHttpResponseInterface_redirectResponse.h \
    $$PWD/http/response/IHttpResponseInterface_statusResponse.h \
    $$PWD/http/response/IHttpResponseManage.h \
    $$PWD/http/response/IHttpResponsePreProcessor.h \
    $$PWD/http/response/IHttpResponseUnit.h \
    $$PWD/http/response/IHttpResponseWare.h \
    $$PWD/http/response/IJsonResponse.h \
    $$PWD/http/response/IPlainTextResponse.h \
    $$PWD/http/response/content/IHttpFileResponseContent.h \
    $$PWD/http/response/content/IHttpInvalidReponseContent.h \
    $$PWD/http/response/content/IHttpResponseContent.h \
    $$PWD/http/session/IHttpSessionAnnomacro.h \
    $$PWD/http/session/IHttpSessionInterface.h \
    $$PWD/http/session/IHttpSessionManager.h \
    $$PWD/http/session/IHttpSessionWare.h

SOURCES += \
    $$PWD/http/IHttpCookieJar.cpp \
    $$PWD/http/IHttpCookiePart.cpp \
    $$PWD/http/IHttpHeaderJar.cpp \
    $$PWD/http/IHttpManage.cpp \
    $$PWD/http/IHttpMultiPart.cpp \
    $$PWD/http/IHttpMultiPartJar.cpp \
    $$PWD/http/IHttpServer.cpp \
    $$PWD/http/IHttpSession.cpp \
    $$PWD/http/IHttpTaskCatagory.cpp \
    $$PWD/http/IRequest.cpp \
    $$PWD/http/IResponse.cpp \
    $$PWD/http/action/IHttpBadRequestAction.cpp \
    $$PWD/http/action/IHttpInternalErrorAction.cpp \
    $$PWD/http/action/IHttpInvalidRequestAction.cpp \
    $$PWD/http/action/IHttpNotFoundAction.cpp \
    $$PWD/http/action/IHttpOptionsMethodAction.cpp \
    $$PWD/http/biscuits/IHttpHeader.cpp \
    $$PWD/http/biscuits/IHttpMethod.cpp \
    $$PWD/http/biscuits/IHttpMime.cpp \
    $$PWD/http/biscuits/IHttpStatus.cpp \
    $$PWD/http/biscuits/IHttpVersion.cpp \
    $$PWD/http/callable/IHttpCallable.cpp \
    $$PWD/http/callable/IHttpReturnType.cpp \
    $$PWD/http/callable/detail/IHttpArgumentTypeDetail.cpp \
    $$PWD/http/callable/detail/IHttpReturnTypeDetail.cpp \
    $$PWD/http/controller/IHttpControllerAction.cpp \
    $$PWD/http/controller/IHttpControllerActionMapping.cpp \
    $$PWD/http/controller/IHttpControllerNode.cpp \
    $$PWD/http/controller/detail/IHttpControllerCallableInfo.cpp \
    $$PWD/http/detail/IHttpRequestImpl.cpp \
    $$PWD/http/detail/IHttpResponseHeader.cpp \
    $$PWD/http/detail/IHttpResponseRaw.cpp \
    $$PWD/http/detail/task/IHttpDefaultProfileTask.cpp \
#    $$PWD/http/detail/task/IHttpFileServiceTask.cpp \
    $$PWD/http/detail/task/IHttpPrintTraceTask.cpp \
    $$PWD/http/detail/task/IHttpResolverFactory.cpp \
    $$PWD/http/invalid/IHttpBadRequestInvalid.cpp \
    $$PWD/http/invalid/IHttpInternalErrorInvalid.cpp \
    $$PWD/http/invalid/IHttpInvalidHandlerWare.cpp \
    $$PWD/http/invalid/IHttpInvalidWare.cpp \
    $$PWD/http/invalid/IHttpNotFoundInvalid.cpp \
    $$PWD/http/path/IHttpPath.cpp \
    $$PWD/http/path/IHttpPathFragment.cpp \
#    $$PWD/http/path/detail/IHttpPathDetail.cpp \
    $$PWD/http/path/detail/IHttpPathFragmentDetail.cpp \
    $$PWD/http/path/detail/IHttpPathValidatorsTask.cpp \
    $$PWD/http/response/IBytesResponse.cpp \
    $$PWD/http/response/IFileResponse.cpp \
    $$PWD/http/response/IHtmlResponse.cpp \
    $$PWD/http/response/IHttpResponseInterface_redirectResponse.cpp \
    $$PWD/http/response/IHttpResponseInterface_statusResponse.cpp \
    $$PWD/http/response/IHttpResponseManage.cpp \
    $$PWD/http/response/IHttpResponseWare.cpp \
    $$PWD/http/response/IJsonResponse.cpp \
    $$PWD/http/response/IPlainTextResponse.cpp \
    $$PWD/http/response/content/IHttpFileResponseContent.cpp \
    $$PWD/http/response/content/IHttpInvalidReponseContent.cpp \
    $$PWD/http/response/content/IHttpResponseContent.cpp \
    $$PWD/http/session/IHttpSessionManager.cpp \
    $$PWD/http/session/IHttpSessionWare.cpp

RESOURCES += \
    $$PWD/http/webresource.qrc
