# SYSTEM AUTO GENERATED DO NOT EDIT!!!
# yuekeyuan@ICore@1.1.0
# core library for IWebCore

current_lib_path = "C:/Users/Yue/IMakeCore/.lib/yuekeyuan@ICore@1.1.0"

INCLUDEPATH += \
    $$current_lib_path

HEADERS += \
    $$current_lib_path/core/abort/IAbortInterface.h \
    $$current_lib_path/core/abort/IAbortPreProcessor.h \
    $$current_lib_path/core/abort/IGlobalAbort.h \
    $$current_lib_path/core/application/iApp.h \
    $$current_lib_path/core/application/IApplication.h \
    $$current_lib_path/core/application/IApplicationAnnomacro.h \
    $$current_lib_path/core/application/IApplicationInterface.h \
    $$current_lib_path/core/application/IApplicationManage.h \
    $$current_lib_path/core/application/IApplicationWare.h \
    $$current_lib_path/core/application/asio/IAsioApplication.h \
    $$current_lib_path/core/application/asio/IAsioContext.h \
    $$current_lib_path/core/application/asio/IAsioTimer.h \
    $$current_lib_path/core/application/qcore/IQCoreApplication.h \
    $$current_lib_path/core/application/qcore/IQCoreContext.h \
    $$current_lib_path/core/application/qcore/IQCoreTimer.h \
    $$current_lib_path/core/application/qgui/IQGuiApplication.h \
    $$current_lib_path/core/base/IException.h \
    $$current_lib_path/core/base/IHandle.h \
    $$current_lib_path/core/base/IJson.h \
    $$current_lib_path/core/base/IResult.h \
    $$current_lib_path/core/base/IString.h \
    $$current_lib_path/core/base/IStringView.h \
    $$current_lib_path/core/base/IStringViewStash.h \
    $$current_lib_path/core/bean/IBeanAbort.h \
    $$current_lib_path/core/bean/IBeanInterface.h \
    $$current_lib_path/core/bean/IBeanInterface_flatten.h \
    $$current_lib_path/core/bean/IBeanPreProcessor.h \
    $$current_lib_path/core/bean/IBeanTypeManage.h \
    $$current_lib_path/core/bean/detail/IBeanInterfaceDetail.h \
    $$current_lib_path/core/config/IConfigAbort.h \
    $$current_lib_path/core/config/IConfigAnnomacro.h \
    $$current_lib_path/core/config/IConfigImportInterface.h \
    $$current_lib_path/core/config/IConfigManageInterface.h \
    $$current_lib_path/core/config/IConfigPreProcessor.h \
    $$current_lib_path/core/config/IConfigTaskCatagory.h \
    $$current_lib_path/core/config/IContextImport.h \
    $$current_lib_path/core/config/IContextManage.h \
    $$current_lib_path/core/config/IContextTaskInterface.h \
    $$current_lib_path/core/config/IProfileImport.h \
    $$current_lib_path/core/config/IProfileManage.h \
    $$current_lib_path/core/config/IProfileTaskInterface.h \
    $$current_lib_path/core/config/default/IContextLoadSystemVariableTask.h \
    $$current_lib_path/core/config/default/ILoadProfileFileUnit.h \
    $$current_lib_path/core/config/default/IProfileLoadJsonTask.h \
    $$current_lib_path/core/task/ITaskAnnomacro.h \
    $$current_lib_path/core/task/ITaskCatagory.h \
    $$current_lib_path/core/task/ITaskCatagoryInterface.h \
    $$current_lib_path/core/task/ITaskManage.h \
    $$current_lib_path/core/task/ITaskPreProcessor.h \
    $$current_lib_path/core/task/ITaskWare.h \
    $$current_lib_path/core/task/default/IBannerTask.h \
    $$current_lib_path/core/task/default/IEndupTaskCatagory.h \
    $$current_lib_path/core/task/default/IEndupTaskInterface.h \
    $$current_lib_path/core/task/default/IInitializationTaskCatagory.h \
    $$current_lib_path/core/task/default/IInitializationTaskInterface.h \
    $$current_lib_path/core/task/default/IRegistBaseTypeTask.h \
    $$current_lib_path/core/task/default/IRegistBaseTypeTask8bit.h \
    $$current_lib_path/core/task/default/IRegistBaseTypeTask8bitChar.h \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskBool.h \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskFloatingPoint.h \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskInt.h \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskJson.h \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskLong.h \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskLongLong.h \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskQString.h \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskShort.h \
    $$current_lib_path/core/task/default/IRegisterBaseTypeTaskString.h \
    $$current_lib_path/core/task/default/IStartupTaskCatagory.h \
    $$current_lib_path/core/task/default/IStartupTaskInterface.h \
    $$current_lib_path/core/task/unit/ITaskCatagoryUnit.h \
    $$current_lib_path/core/task/unit/ITaskInstantUnit.h \
    $$current_lib_path/core/task/unit/ITaskWareUnit.h \
    $$current_lib_path/core/test/IFunctionTestInterface.h \
    $$current_lib_path/core/test/IIntegrationTestInterface.h \
    $$current_lib_path/core/test/ITestCatagory.h \
    $$current_lib_path/core/test/ITestManage.h \
    $$current_lib_path/core/test/ITestTaskInterface.h \
    $$current_lib_path/core/test/IUnitTestInterface.h \
    $$current_lib_path/core/test/default/IFunctionTestTask.h \
    $$current_lib_path/core/test/default/IIntegrationTestTask.h \
    $$current_lib_path/core/test/default/IUnitTestTask.h \
    $$current_lib_path/core/unit/IGadgetUnit.h \
    $$current_lib_path/core/unit/INoConstructUnit.h \
    $$current_lib_path/core/unit/INoCopyMoveUnit.h \
    $$current_lib_path/core/unit/IOrderUnit.h \
    $$current_lib_path/core/unit/IRegisterMetaTypeUnit.h \
    $$current_lib_path/core/unit/ISoloUnit.h \
    $$current_lib_path/core/unit/IStackObjectUnit.h \
    $$current_lib_path/core/unit/ITraceUnit.h \
    $$current_lib_path/core/util/ICodecUtil.h \
    $$current_lib_path/core/util/IConstantUtil.h \
    $$current_lib_path/core/util/IConvertUtil.h \
    $$current_lib_path/core/util/IFileUtil.h \
    $$current_lib_path/core/util/IHeaderUtil.h \
    $$current_lib_path/core/util/IJsonUtil.h \
    $$current_lib_path/core/util/IMetaUtil.h \
    $$current_lib_path/core/util/IPackageUtil.h \
    $$current_lib_path/core/util/IPreProcessorUtil.h \
    $$current_lib_path/core/util/ISpawnUtil.h \
    $$current_lib_path/core/util/IStringUtil.h \
    $$current_lib_path/core/util/ITicTacUtil.h \
    $$current_lib_path/core/util/ITraitUtil.h \
    $$current_lib_path/core/util/detail/IJsonUtil_fromJson.h \
    $$current_lib_path/core/util/detail/IJsonUtil_toJson.h

SOURCES += \
    $$current_lib_path/core/abort/IGlobalAbort.cpp \
    $$current_lib_path/core/application/iApp.cpp \
    $$current_lib_path/core/application/IApplication.cpp \
    $$current_lib_path/core/application/IApplicationManage.cpp \
    $$current_lib_path/core/application/IApplicationWare.cpp \
    $$current_lib_path/core/application/asio/IAsioApplication.cpp \
    $$current_lib_path/core/application/asio/IAsioContext.cpp \
    $$current_lib_path/core/application/asio/IAsioTimer.cpp \
    $$current_lib_path/core/application/qcore/IQCoreApplication.cpp \
    $$current_lib_path/core/application/qcore/IQCoreContext.cpp \
    $$current_lib_path/core/application/qcore/IQCoreTimer.cpp \
    $$current_lib_path/core/application/qgui/IQGuiApplication.cpp \
    $$current_lib_path/core/base/IException.cpp \
    $$current_lib_path/core/base/IJson.cpp \
    $$current_lib_path/core/base/IString.cpp \
    $$current_lib_path/core/base/IStringView.cpp \
    $$current_lib_path/core/base/IStringViewStash.cpp \
    $$current_lib_path/core/base/IString_value.cpp \
    $$current_lib_path/core/bean/IBeanInterface.cpp \
    $$current_lib_path/core/bean/IBeanTypeManage.cpp \
    $$current_lib_path/core/bean/detail/IBeanInterfaceDetail.cpp \
    $$current_lib_path/core/config/IConfigManageInterface.cpp \
    $$current_lib_path/core/config/IConfigTaskCatagory.cpp \
    $$current_lib_path/core/config/IContextImport.cpp \
    $$current_lib_path/core/config/IProfileImport.cpp \
    $$current_lib_path/core/config/IProfileManage.cpp \
    $$current_lib_path/core/config/default/IContextLoadSystemVariableTask.cpp \
    $$current_lib_path/core/config/default/ILoadProfileFileUnit.cpp \
    $$current_lib_path/core/config/default/IProfileLoadJsonTask.cpp \
    $$current_lib_path/core/task/ITaskCatagory.cpp \
    $$current_lib_path/core/task/ITaskManage.cpp \
    $$current_lib_path/core/task/ITaskWare.cpp \
    $$current_lib_path/core/task/default/IBannerTask.cpp \
    $$current_lib_path/core/task/default/IEndupTaskCatagory.cpp \
    $$current_lib_path/core/task/default/IInitializationTaskCatagory.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTask.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTask8bit.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTask8bitChar.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskBool.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskFloatingPoint.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskInt.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskJson.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskLong.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskLongLong.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskQString.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskShort.cpp \
    $$current_lib_path/core/task/default/IRegistBaseTypeTaskString.cpp \
    $$current_lib_path/core/task/default/IStartupTaskCatagory.cpp \
    $$current_lib_path/core/test/ITestCatagory.cpp \
    $$current_lib_path/core/test/ITestManage.cpp \
    $$current_lib_path/core/test/IUnitTestManage.cpp \
    $$current_lib_path/core/test/default/IFunctionTestTask.cpp \
    $$current_lib_path/core/test/default/IIntegrationTestTask.cpp \
    $$current_lib_path/core/test/default/IUnitTestTask.cpp \
    $$current_lib_path/core/unit/ISoloUnit.cpp \
    $$current_lib_path/core/util/ICodecUtil.cpp \
    $$current_lib_path/core/util/IConvertUtil.cpp \
    $$current_lib_path/core/util/IFileUtil.cpp \
    $$current_lib_path/core/util/IMetaUtil.cpp \
    $$current_lib_path/core/util/IStringUtil.cpp \
    $$current_lib_path/core/util/ITicTacUtil.cpp

